-- ユーザーテストデータ（20人）

INSERT INTO users (employee_id, name, position, created_at, updated_at) VALUES
-- パートナー（2人）
('100001', '山田太郎', 'PARTNER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('100002', '佐藤花子', 'PARTNER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- シニアマネージャー（3人）
('100003', '鈴木一郎', 'SENIOR_MANAGER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('100004', '田中美咲', 'SENIOR_MANAGER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('100005', '高橋健太', 'SENIOR_MANAGER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- マネージャー（4人）
('100006', '伊藤愛', 'MANAGER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('100007', '渡辺翔太', 'MANAGER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('100008', '中村優子', 'MANAGER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('100009', '小林大輔', 'MANAGER', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- シニアスタッフ（5人）
('100010', '加藤梨花', 'SENIOR_CONSULTANT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('100011', '吉田直樹', 'SENIOR_CONSULTANT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('100012', '山本さくら', 'SENIOR_CONSULTANT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('100013', '松本隼人', 'SENIOR_CONSULTANT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('100014', '井上瑞希', 'SENIOR_CONSULTANT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- スタッフ（4人）
('100015', '木村拓也', 'CONSULTANT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('100016', '林麻衣', 'CONSULTANT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('100017', '清水陽介', 'CONSULTANT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('100018', '森野あかり', 'CONSULTANT', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),

-- ジュニアスタッフ（2人）
('100019', '池田蓮', 'ANALYST', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
('100020', '斎藤結衣', 'ANALYST', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
